### ISSUE TITLE
Update Qr-Scanner example for 0.2.8

### ISSUE THREAD

**Issue by jpbaltazar** [reflex-dev/reflex-examples#153]
Hi, I'm a pretty avid user of the [qr-scanner example](https://github.com/reflex-dev/reflex-examples/tree/main/qr-scanner) and I've seen warnings that the `rx.EVENT_ARG` instances are outdated and should be replaced by the event API. 

How would someone fix this example?

**Comment by picklelo** [comment]
Looks like this will be resolved in #155
