### ISSUE TITLE
local_auth is missing.

### ISSUE THREAD

**Issue by INF800** [reflex-dev/reflex-examples#284]
I cannot find the folder `local_auth` mentioned in this blog: https://dev.to/emmakodes_/setup-user-auth-for-your-reflex-app-using-localauth-4nj8

Is local authentication suggested or not suggested with reflex??

**Comment by picklelo** [comment]
@INF800 Check out [this page](https://reflex.dev/docs/authentication/authentication-overview/) on auth - it includes a link to an app using local auth.

**Comment by INF800** [comment]
Thanks @picklelo
